version: "3"
services:
  bootnode:
    hostname: bootnode
    build:
      context: ./bootnode
    ports:
      - 30301:30301/udp
    networks:
      chain:
        ipv4_address: 172.25.0.101

  node-1:
    hostname: node-1
    depends_on:
      - bootnode
    environment:
      - account=0
      - bootnodeId=5989d09f7fcd113e90501cdd7c136400199fc186330599a3d97586e1e68987f5833c09223e54e010d5b42ddae4b43b23d72768930c5946baf9a12494ce9dc91d
      - bootnodeIp=172.25.0.101
    build:
      context: ./node
    container_name: node-1
    networks:
      chain:
        ipv4_address: 172.25.0.102

  node-2:
    hostname: node-2
    depends_on:
      - bootnode
    environment:
      - account=1
      - bootnodeId=5989d09f7fcd113e90501cdd7c136400199fc186330599a3d97586e1e68987f5833c09223e54e010d5b42ddae4b43b23d72768930c5946baf9a12494ce9dc91d
      - bootnodeIp=172.25.0.101
    build:
      context: ./node
    container_name: node-2
    networks:
      chain:
        ipv4_address: 172.25.0.103

  node-dev:
    hostname: node-dev
    depends_on:
      - bootnode
    environment:
      - bootnodeId=5989d09f7fcd113e90501cdd7c136400199fc186330599a3d97586e1e68987f5833c09223e54e010d5b42ddae4b43b23d72768930c5946baf9a12494ce9dc91d
      - bootnodeIp=172.25.0.101
    build:
      context: ./node_dev
    container_name: node-dev
    ports:
      - 8545:8545
    healthcheck:
      test: wget http://localhost:8545
      interval: 2s
      timeout: 5s
      retries: 30
    networks:
      chain:
        ipv4_address: 172.25.0.104

networks:
  chain:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
